services:
  app:
    build: .
    container_name: symfony-testing
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    command: symfony server:start --port=8000  --no-tls --allow-http --allow-all-ip --dir=public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.symfony-testing.rule=Host(`symfony-testing.localhost`)"
      - "traefik.http.services.symfony-testing.loadbalancer.server.port=8000"
    networks:
      - docker-dev

networks:
  docker-dev:
    external: true
