services:
  app:
    build: .
    container_name: symfony-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    command: | 
      sh -c " 
      bin/console doctrine:database:create --if-not-exists && 
      bin/console doctrine:migrations:migrate --no-interaction && 
      bin/console doctrine:fixtures:load --no-interaction && 
      symfony server:start --port=8000  --no-tls --allow-http --allow-all-ip --dir=public"
  db:
    image: mysql:8.0
    container_name: symfony-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony-test
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot --silent || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33666:3306"

volumes:
    db_data: ~