services:
  app:
    build: .
    container_name: symfony-testing
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    command: symfony server:start --port=8000  --no-tls --allow-http --allow-all-ip --dir=public
  db:
    image: mysql:8.0
    container_name: symfony-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony-test
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data: ~